### ISSUE TITLE
Shouldn't we delete first and then build?

### ISSUE THREAD

**Issue by sumitramanga** [MindscapeHQ/raygun4node-aws-lambda#10]
https://github.com/MindscapeHQ/raygun4node-aws-lambda/blob/230e9e928158475a420cff6dede94126be8d9de4/example/prepare.sh#L14-L17

**Comment by miquelbeltran** [comment]
We do that, the first build step (lines 7 to 12) is building the aws-lambda package. 

The example gets build in lines 19 to 23, so after the zip file is deleted.

Anyway, it won't matter much as long as the old zip file is deleted before creating the new one.

Closing as this question was responded.
