### ISSUE TITLE
Would it not be >= 2 if there are multiple handlers?

### ISSUE THREAD

**Issue by sumitramanga** [MindscapeHQ/raygun4node-aws-lambda#11]
https://github.com/MindscapeHQ/raygun4node-aws-lambda/blob/62ce4333ba033114f46d37a31f42468dc9d25d8b/lib/raygun.aws.ts#L77

**Comment by miquelbeltran** [comment]
This doesn't check the amount of handlers, but the amount of parameters in the provided handler.
