### ISSUE TITLE
Add read -p "Press any key to exit..." at the the end of the prepare.sh script

### ISSUE THREAD

**Issue by sumitramanga** [MindscapeHQ/raygun4node-aws-lambda#17]
I encountered an error but could not debug properly since the terminal would close once the script was done executing. Adding in this line helped me out in knowing, I just didn't have `zip` installed!

https://github.com/MindscapeHQ/raygun4node-aws-lambda/blob/62ce4333ba033114f46d37a31f42468dc9d25d8b/example/prepare.sh#L28

**Comment by miquelbeltran** [comment]
I will check if this affects users running the script from the command line.

**Comment by miquelbeltran** [comment]
I'll prefer to add a note to the README asking users to run the script from the command line, so they can see any output.

Otherwise, each time I run the script when testing, I need to tap a key again.
