### ISSUE TITLE
Remove all commented out code from tsconfig.json

### ISSUE THREAD

**Issue by sumitramanga** [MindscapeHQ/raygun4node-aws-lambda#2]
https://github.com/MindscapeHQ/raygun4node-aws-lambda/blob/230e9e928158475a420cff6dede94126be8d9de4/tsconfig.json#L4

**Comment by miquelbeltran** [comment]
I'll clean this up.

FYI, the `tsconfig.json` file is the same as in the raygun4node repo, including all the commented out lines.
