### ISSUE TITLE
Clarity required - Does the user install 2 packages or 1. Also not sure if the order matters but it would be good to first install the raygun4node and this Lambda package 

### ISSUE THREAD

**Issue by sumitramanga** [MindscapeHQ/raygun4node-aws-lambda#3]
https://github.com/MindscapeHQ/raygun4node-aws-lambda/blob/230e9e928158475a420cff6dede94126be8d9de4/README.md?plain=1#L16-L18

**Comment by miquelbeltran** [comment]
Order should not matter. I think the user has to install both aws-lambda and raygun, because they need to import the raygun reference to init the client. I'll try to clarify.
