### ISSUE TITLE
Wire up these github templates

### ISSUE THREAD

**Issue by sumitramanga** [MindscapeHQ/raygun4node-aws-lambda#6]
From memory, I need to do this?

https://github.com/MindscapeHQ/raygun4node-aws-lambda/blob/230e9e928158475a420cff6dede94126be8d9de4/.github/ISSUE_TEMPLATE/bug_report.md?plain=1#L2

**Comment by sumitramanga** [comment]
@miquelbeltran  If there's anything else I need to enable in settings please lmk (branch protection might be one)

**Comment by sumitramanga** [comment]
Actually the templates are working. Just not when you reference some code to make an issue with!

**Comment by miquelbeltran** [comment]
Yes, these seems correct already:

![image](https://github.com/MindscapeHQ/raygun4node-aws-lambda/assets/2494376/da1fd5d0-c78a-4dc2-9007-10a68957da54)

I'll close this ticket!
