### ISSUE TITLE
Is this file required?

### ISSUE THREAD

**Issue by sumitramanga** [MindscapeHQ/raygun4node-aws-lambda#8]
https://github.com/MindscapeHQ/raygun4node-aws-lambda/blob/230e9e928158475a420cff6dede94126be8d9de4/example/package.json#L1-L9

**Comment by miquelbeltran** [comment]
Yes, because you still have to install the dependencies (raygun4node package).

The `prepare.sh` package takes care of that!

Closing as the question should be resolved.
